### ISSUE TITLE
Undocumented Code

### ISSUE THREAD

**Issue by Prakriti-nith** [sunidhichaudhary/transition-animation-in-css#2]
I am unable to understand the working of your code. Can you please provide the documentation? @sunidhichaudhary just out of curiosity, is there any significance of the class 'ponga' [here](https://github.com/sunidhichaudhary/transition-animation-in-css/blob/master/website.html#L18).

**Comment by sunidhichaudhary** [comment]
No, I can't provide the documentation @Prakriti-nith
